name: 'Demo Company Profile (Thex Theme)'
description: 'Sets up a Company Profile demo site using Thex theme with custom corporate branding CSS'
type: 'Site'

install:
  - node
  - block
  - system
  - user
  - claro
  - asset_injector
  - thex

recipes:
  - core/recipes/page_content_type
  - core/recipes/full_html_format_editor

config:
  import:
    asset_injector: '*'
  actions:
    system.theme:
      simpleConfigUpdate:
        default: 'thex'
        admin: 'claro'
    user.settings:
      simpleConfigUpdate:
        register: 'admin_only'
    system.site:
      simpleConfigUpdate:
        name: 'Saha Akanee Public Company Limited'
        slogan: 'Innovation for Future'
        page.front: '/home'
